function TableS5 = importDataGroup5(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TABLES5 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  TABLES5 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  TableS5 = importfile("D:\WORK\ADAM Course\ADAM Course and Plan\Datasets\Tables\Table S5.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Aug-2022 18:44:04

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 165);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Var1", "CE171", "CE202", "CerD181180", "CerD181200", "CerD181241", "CerD182241", "DG181_160", "DG181_180", "DG181_181", "DG204_160", "DG201_181", "DG201_182", "DG204_180", "DG224_181", "FA201", "FA241", "Hex2CerD161160", "Hex2CerD181140", "Hex2CerD182160", "HexCerD161220", "HexCerD161240", "HexCerD181220", "HexCerD182220", "HexCerD181230", "HexCerD181240", "HexCerD182240", "LPC151", "LPC210", "LPC220", "LPC240", "LPC250", "LPC260", "LPCO160", "LPCO161", "LPE160", "LPE180", "LPE181", "LPE204", "PC271", "PC281", "PC282", "PC291", "PC303", "PC312", "PC335", "PC345", "PC352", "PC353", "PC367", "PC394", "PC397", "PC404", "PC408", "PC409", "PC412", "PC413", "PC414", "PC415", "PC4210", "PC4211", "PC422", "PC424", "PC428", "PC429", "PC432", "PC4410", "PC4412", "PC464", "PC465", "PC466", "PCO260", "PCO290", "PCO300", "PCO301", "PCO310", "PCO330", "PCO342", "PCO343", "PCO344", "PCO353", "PCO362", "PCO363", "PCO364", "PCO366", "PCO382", "PCO383", "PCO386", "PCO387", "PCO406", "PCO407", "PCO426", "PCO444", "PE320", "PE321", "PE341", "PE342", "PE352", "PE361", "PE362", "PE363", "PE364", "PE384", "PE407", "PEO364", "PE160p_205", "PEO384", "PE180p_204", "PEO386", "PE180p_205", "PEO406", "PE180p_226", "SM291", "SM302", "SM311", "SM321", "SM322", "SM330", "SM331", "SM343", "SM352", "SM353", "SM371", "SM372", "SM373", "SM386", "SM391", "SM392", "SM412", "SM422", "SM424", "SM443", "SM444", "TG480160_X_X", "TG500160_X_X", "TG501160_X_X", "TG502160_X_X", "TG521180_X_X", "TG5221160_X_X", "TG5222161_X_X", "TG523160_X_X", "TG5311180_X_X", "TG5312160_X_X", "TG537151_X_X", "TG5421160_X_X", "TG5422180_X_X", "TG5431181_X_X", "TG5432180_X_X", "TG544181_X_X", "TG5521181_X_X", "TG5522180_X_X", "TG553181_X_X", "TG554181_X_X", "TG562160_X_X", "TG563201_X_X", "TG564201_X_X", "TG565224_X_X", "TG5661181_X_X", "TG5662202_X_X", "TG583181_X_X", "TG5841181_X_X", "TG5842201_X_X", "TG586181_X_X", "TG602180_X_X", "Var165"];
opts.SelectedVariableNames = ["CE171", "CE202", "CerD181180", "CerD181200", "CerD181241", "CerD182241", "DG181_160", "DG181_180", "DG181_181", "DG204_160", "DG201_181", "DG201_182", "DG204_180", "DG224_181", "FA201", "FA241", "Hex2CerD161160", "Hex2CerD181140", "Hex2CerD182160", "HexCerD161220", "HexCerD161240", "HexCerD181220", "HexCerD182220", "HexCerD181230", "HexCerD181240", "HexCerD182240", "LPC151", "LPC210", "LPC220", "LPC240", "LPC250", "LPC260", "LPCO160", "LPCO161", "LPE160", "LPE180", "LPE181", "LPE204", "PC271", "PC281", "PC282", "PC291", "PC303", "PC312", "PC335", "PC345", "PC352", "PC353", "PC367", "PC394", "PC397", "PC404", "PC408", "PC409", "PC412", "PC413", "PC414", "PC415", "PC4210", "PC4211", "PC422", "PC424", "PC428", "PC429", "PC432", "PC4410", "PC4412", "PC464", "PC465", "PC466", "PCO260", "PCO290", "PCO300", "PCO301", "PCO310", "PCO330", "PCO342", "PCO343", "PCO344", "PCO353", "PCO362", "PCO363", "PCO364", "PCO366", "PCO382", "PCO383", "PCO386", "PCO387", "PCO406", "PCO407", "PCO426", "PCO444", "PE320", "PE321", "PE341", "PE342", "PE352", "PE361", "PE362", "PE363", "PE364", "PE384", "PE407", "PEO364", "PE160p_205", "PEO384", "PE180p_204", "PEO386", "PE180p_205", "PEO406", "PE180p_226", "SM291", "SM302", "SM311", "SM321", "SM322", "SM330", "SM331", "SM343", "SM352", "SM353", "SM371", "SM372", "SM373", "SM386", "SM391", "SM392", "SM412", "SM422", "SM424", "SM443", "SM444", "TG480160_X_X", "TG500160_X_X", "TG501160_X_X", "TG502160_X_X", "TG521180_X_X", "TG5221160_X_X", "TG5222161_X_X", "TG523160_X_X", "TG5311180_X_X", "TG5312160_X_X", "TG537151_X_X", "TG5421160_X_X", "TG5422180_X_X", "TG5431181_X_X", "TG5432180_X_X", "TG544181_X_X", "TG5521181_X_X", "TG5522180_X_X", "TG553181_X_X", "TG554181_X_X", "TG562160_X_X", "TG563201_X_X", "TG564201_X_X", "TG565224_X_X", "TG5661181_X_X", "TG5662202_X_X", "TG583181_X_X", "TG5841181_X_X", "TG5842201_X_X", "TG586181_X_X", "TG602180_X_X"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var165"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var165"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["CE171", "CE202", "CerD181180", "CerD181200", "DG181_180", "DG204_160", "DG201_181", "DG201_182", "DG204_180", "DG224_181", "Hex2CerD161160", "Hex2CerD181140", "Hex2CerD182160", "HexCerD161220", "HexCerD161240", "HexCerD182220", "HexCerD182240", "LPC151", "LPC210", "LPC220", "LPC240", "LPC250", "LPC260", "LPCO160", "LPCO161", "PC271", "PC303", "PC335", "PC367", "PC409", "PC412", "PC415", "PC4211", "PC422", "PC424", "PC429", "PC432", "PC4410", "PC4412", "PC464", "PC465", "PC466", "PCO260", "PCO290", "PCO301", "PCO330", "PCO444", "PE320", "PE321", "PE352", "PE160p_205", "SM291", "SM302", "SM311", "SM330", "SM343", "SM353", "SM373", "SM386", "SM443", "SM444", "TG5311180_X_X", "TG5312160_X_X", "TG537151_X_X", "TG5521181_X_X", "TG5522180_X_X", "TG553181_X_X", "TG554181_X_X", "TG562160_X_X", "TG563201_X_X", "TG564201_X_X", "TG565224_X_X", "TG583181_X_X", "TG5841181_X_X", "TG5842201_X_X", "TG586181_X_X", "TG602180_X_X"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["CE171", "CE202", "CerD181180", "CerD181200", "DG181_180", "DG204_160", "DG201_181", "DG201_182", "DG204_180", "DG224_181", "Hex2CerD161160", "Hex2CerD181140", "Hex2CerD182160", "HexCerD161220", "HexCerD161240", "HexCerD182220", "HexCerD182240", "LPC151", "LPC210", "LPC220", "LPC240", "LPC250", "LPC260", "LPCO160", "LPCO161", "PC271", "PC303", "PC335", "PC367", "PC409", "PC412", "PC415", "PC4211", "PC422", "PC424", "PC429", "PC432", "PC4410", "PC4412", "PC464", "PC465", "PC466", "PCO260", "PCO290", "PCO301", "PCO330", "PCO444", "PE320", "PE321", "PE352", "PE160p_205", "SM291", "SM302", "SM311", "SM330", "SM343", "SM353", "SM373", "SM386", "SM443", "SM444", "TG5311180_X_X", "TG5312160_X_X", "TG537151_X_X", "TG5521181_X_X", "TG5522180_X_X", "TG553181_X_X", "TG554181_X_X", "TG562160_X_X", "TG563201_X_X", "TG564201_X_X", "TG565224_X_X", "TG583181_X_X", "TG5841181_X_X", "TG5842201_X_X", "TG586181_X_X", "TG602180_X_X"], "ThousandsSeparator", ",");

% Import the data
TableS5 = readtable(filename, opts);

end